# Generated by Django 2.1.2 on 2018-10-29 04:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('contact_name', models.CharField(max_length=50, verbose_name='contact name')),
                ('address_one', models.CharField(max_length=50, verbose_name='address one')),
                ('address_two', models.CharField(blank=True, max_length=50, verbose_name='address two')),
                ('town', models.CharField(max_length=50, verbose_name='town')),
                ('county', models.CharField(blank=True, max_length=50, verbose_name='county')),
                ('postcode', models.CharField(max_length=50, verbose_name='postcode')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Display only'), (2, 'Deleted')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='ISO code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.Country', verbose_name='country'),
        ),
    ]
